import { AbsoluteFill, Audio, Sequence, interpolate, staticFile, useCurrentFrame } from 'remotion';
import {
  FPS,
  OSWALD_URL,
  HARD_CUT_FRAMES,
  KenBurnsImage,
  Vignette,
  ContextTag,
  useGoldOverlay,
  CaptionOverlay,
  EndCardCTA,
  GOLD,
  CANVAS_HEIGHT,
  SAFE_ZONE_BOTTOM_Y,
  type SlideConfig as SharedSlideConfig,
} from '../shared/QuickStrikeShared';

// Antietam BLUEGRAY Quick Strike.
//
// Locked decisions from the build brief:
//   - No fades anywhere: true cold open at frame 0 (handled by SlidePanel's
//     isFirst prop), hard cut on every other slide, no fade to black at the
//     end (end card renders at constant opacity 1 -- see EndCard below).
//   - Per-slide audio only (one <Audio> per Sequence) -- no continuous track.
//   - Three-layer text system on slides 1-4:
//       1. ContextTag (`label`) -- short persistent top-left tag.
//       2. CaptionOverlay (`captionLines`) -- the locked VO script,
//          verbatim, split into per-clause cues that word-time against
//          each slide's own audioDurationFrames.
//       3. GoldLowerThird (`overlayText`) -- a short ADDITIVE line (not a
//          repeat of the caption), giving silent viewers context the VO
//          doesn't state out loud. Omitted on slide 1 (too short for two
//          text blocks).
//     STACKING ORDER (swapped from the shared SlidePanel default): CaptionOverlay
//     is bottom-anchored, hugging SAFE_ZONE_BOTTOM_Y exactly, and the headline
//     is repositioned every frame to sit just above whichever caption cue is
//     currently active -- the reverse of SlidePanel's baked-in wiring (headline
//     fixed at the bottom, caption computed to avoid it). SlidePanel's own
//     prop surface has no way to express "headline reacts to caption," so
//     slides 1-4 use a local ContentSlide component below instead of SlidePanel,
//     composed from the same shared building blocks (KenBurnsImage, Vignette,
//     ContextTag, CaptionOverlay) plus a local HeadlineBox in place of
//     GoldLowerThird (also local -- see HeadlineBox for why: it needed a
//     vertical-padding trim GoldLowerThird's props don't expose, on top of the
//     positioning reversal). The reversal itself uses HeadlineBox's
//     bottomOffset prop (mirrors GoldLowerThird's own -- public API either way,
//     no shared-file edits) to push the headline up by however tall the active
//     caption cue's box currently is -- see ContentSlide below for the exact
//     math, which duplicates CaptionOverlay's own internal (non-exported)
//     line-wrap/height formulas since there's no way to read that back out of
//     the locked component otherwise.
//   - Pan-Fill scale/pan math: pan mode holds scale FIXED at baseScale
//     (= CANVAS_HEIGHT / sourceHeight, the zoom that fills the canvas
//     height) and only animates translateX within the image's own
//     overflow past 1080px at that scale (panRoomPx). The image can
//     therefore never reveal its edge no matter how far it pans, which is
//     exactly the invariant the legacy manual-motion rule (scale >=1.06 for
//     pan >20px, >=1.08 for >30px) protected against by hand -- Pan-Fill
//     satisfies it structurally, not via a tuned scale value.

const PAD_S = 0.4;

// This composition's own safe-zone boundary -- 10px looser than the shared
// engine's default SAFE_ZONE_BOTTOM_Y (1580), via the additive
// safeZoneBottomY prop now on GoldLowerThird/CaptionOverlay/SlidePanel/
// EndCardCTA. Scoped to Antietam only: every other composition omits this
// prop and keeps the 1580 default untouched. Margin check (see the chat
// history / render comparison this shipped with): with this value, every
// content slide's caption bottom edge lands at y=1570 -- 30px clear of the
// y=1600 flag-risk threshold a real published video hit before.
const ANTIETAM_SAFE_ZONE_BOTTOM_Y = 1590;

// Actual measured VO durations (Kokoro am_adam/0.95/en-us, ffprobe-verified).
// Slide 1 is from the original generateVoiceover-antietam.py pass (text
// unaffected by any pronunciation fix). Slides 2-4 and the end card were
// regenerated by scripts/generateVoiceover-antietam-phoneme-fix.py, which
// supersedes an earlier grapheme-respelling attempt
// (generateVoiceover-antietam-pronunciation-fix.py, "An-tee-tuhm" as plain
// text) that turned out to make things worse -- hyphenating a respelling
// makes espeak treat it as one glued-together fake word with wrong stress/
// vowels. The phoneme-fix script instead phonemizes each sentence with
// correct spelling throughout and splices in a hand-built correct phoneme
// sequence for just the mispronounced word. Slide 2's Maryland fix went
// through two rounds: v2 (generateVoiceover-antietam-phoneme-fix-v2.py)
// guessed mˈɛɹəlʌnd ("MEHR-uh-lund"), which turned out wrong by ear; v3
// (generateVoiceover-antietam-phoneme-fix-v3.py, current) uses mˈɛɹɪlənd
// ("MEHR-ih-luhnd"), confirmed correct via an A/B of standalone
// single-word clips. Either way, the displayed captionLines/end-card text
// below keep the standard spelling -- none of this reaches the screen.
const SLIDE1_AUDIO_S = 1.802;
const SLIDE2_AUDIO_S = 10.658;
const SLIDE3_AUDIO_S = 9.535;
const SLIDE4_AUDIO_S = 7.967;
const CTA_AUDIO_S = 4.624;

type SlideConfig = SharedSlideConfig & {
  sourceWidth: number;
  sourceHeight: number;
};

const SLIDES: SlideConfig[] = [
  {
    id: 'slide1',
    image: 'slides/Antietam/01-antietam-fence-line-dead.jpg',
    audio: 'audio/antietam/slide1.mp3',
    durationInSeconds: SLIDE1_AUDIO_S + PAD_S,
    audioDurationSeconds: SLIDE1_AUDIO_S,
    label: '1862',
    // No overlayText -- 2.2s is too short to read two text blocks, so this
    // slide is ContextTag + CaptionOverlay only. CaptionOverlay always hugs
    // the safe-zone line now (see ContentSlide), so this slide's caption
    // behaves identically to every other slide's -- there's just no
    // headline above it to worry about.
    captionLines: ['You have the wrong bloodiest day.'],
    // 6202x4344, aspect 1.428 -- above PAN_FILL_ASPECT_THRESHOLD (1.2) so
    // Pan-Fill would auto-pan, but the slide is only 2.2s -- too short to
    // read as intentional motion -- so panFillMode is forced to 'static'.
    // Pan-Fill's static category applies its own subtle scale-only drift
    // (PAN_FILL_STATIC_SCALE_TO) automatically since no explicit `motion`
    // is passed here, giving the "minimal drift only" the brief calls for.
    sourceWidth: 6202,
    sourceHeight: 4344,
    panFillMode: 'static',
  },
  {
    id: 'slide2',
    image: 'slides/Antietam/02-antietam-battlefield-dead.jpg',
    audio: 'audio/antietam/slide2.mp3',
    durationInSeconds: SLIDE2_AUDIO_S + PAD_S,
    audioDurationSeconds: SLIDE2_AUDIO_S,
    label: 'SHARPSBURG, MARYLAND',
    // Additive line -- not in the VO, gives silent viewers the "where"
    // the audio never states. Wraps to ~2 lines at the default fontSize 52
    // (~66 chars against the ~768px effective wrap width). Under the
    // swapped stacking order this box now FLOATS -- ContentSlide repositions
    // it every frame to sit just above whichever caption cue below is
    // currently active, so its on-screen height doesn't need to be
    // hand-checked against the captions; that clearance is enforced
    // dynamically at render time regardless of cue length.
    overlayText: "Fought across the Cornfield, the Sunken Road, and Burnside's Bridge",
    // VO verbatim, split into per-clause caption cues (unchanged wording,
    // just chunked so each cue tracks the speech instead of dumping the
    // whole paragraph on screen at once). Each cue's box now hugs
    // SAFE_ZONE_BOTTOM_Y exactly (fixed position, doesn't move) -- it's
    // GoldLowerThird above that moves to avoid IT, not the other way around.
    // Longest cues ("September seventeenth..." / "Twenty-two thousand...")
    // are checked against 2-line wraps via rendered stills below.
    captionLines: [
      'The Battle of Antietam.',
      'September seventeenth, eighteen sixty-two, near Sharpsburg, Maryland.',
      'Twenty-two thousand seven hundred Americans, dead, wounded, or missing.',
      'In twelve hours.',
    ],
    // 3385x1990, aspect 1.701 -- at/above the pan threshold, so 'auto' would
    // already resolve to 'pan'; set explicitly per spec. baseScale =
    // 1920/1990 ~= 0.965, panRoomPx ~= 2187, and PAN_FILL_RANGE_FRACTION
    // (0.875, the shared default) puts usable pan room at ~1914px -- the
    // ~87.5%-of-room the brief calls for. Actual pan distance is further
    // capped by MAX_PAN_SPEED_PX_PER_SEC over this slide's 11.07s duration
    // (post phoneme-fix re-time, ~1107px), so the pan stays centered in
    // that usable room rather than running edge to edge.
    sourceWidth: 3385,
    sourceHeight: 1990,
    panFillMode: 'pan',
    panDirection: 'ltr',
  },
  {
    id: 'slide3',
    image: 'slides/Antietam/03-antietam-dunker-church.jpg',
    audio: 'audio/antietam/slide3.mp3',
    durationInSeconds: SLIDE3_AUDIO_S + PAD_S,
    audioDurationSeconds: SLIDE3_AUDIO_S,
    label: 'SEPT 19-22, 1862',
    // Additive line -- where the photographs actually surfaced, which the
    // VO doesn't say.
    overlayText: 'Exhibited weeks later in New York City',
    // VO verbatim, split at the sentence boundary into two caption cues.
    captionLines: [
      'Photographer Alexander Gardner reached the Antietam battlefield before the bodies were buried.',
      'No one had ever seen American war dead in a photograph before.',
    ],
    // 3012x2587, aspect 1.164 -- BELOW PAN_FILL_ASPECT_THRESHOLD (1.2), so
    // 'auto' would resolve to 'static'; forced to 'pan' per spec. baseScale
    // = 1920/2587 ~= 0.742, panRoomPx ~= 1156, usable pan room (87.5%) ~=
    // 1011px, and this slide's 9.93s duration (post pronunciation-fix
    // re-time) caps the speed-limited pan distance at ~993px -- effectively
    // the full usable room.
    sourceWidth: 3012,
    sourceHeight: 2587,
    panFillMode: 'pan',
    panDirection: 'ltr',
  },
  {
    id: 'slide4',
    image: 'slides/Antietam/04-antietam-lincoln-generals.jpg',
    audio: 'audio/antietam/slide4.mp3',
    durationInSeconds: SLIDE4_AUDIO_S + PAD_S,
    audioDurationSeconds: SLIDE4_AUDIO_S,
    label: 'SEPT 22, 1862',
    // Additive line -- the date the VO's "strategic success" actually took
    // effect, which it doesn't state. Not spoken, so the numerals don't
    // need to be spelled out per the Kokoro rule (that rule only applies to
    // text that gets synthesized).
    overlayText: 'The final Proclamation took effect January 1, 1863',
    // VO verbatim, split at the comma into two caption cues.
    captionLines: [
      'Five days after Antietam,',
      "President Lincoln used the Union's strategic success to issue the Preliminary Emancipation Proclamation.",
    ],
    // 4504x3324, aspect 1.355 -- above the pan threshold, so 'auto' would
    // pan; forced to 'static' -- this is a formal group photo, and panning
    // a lineup doesn't reveal anything. Static keeps Lincoln identifiable
    // from frame 0, with Pan-Fill's default subtle static drift applied.
    sourceWidth: 4504,
    sourceHeight: 3324,
    panFillMode: 'static',
  },
];

const slidesWithFrames = SLIDES.map((s) => ({
  ...s,
  durationFrames: Math.round(s.durationInSeconds * FPS),
  audioDurationFrames: Math.round(s.audioDurationSeconds * FPS),
}));

const slidesDuration = slidesWithFrames.reduce((sum, s) => sum + s.durationFrames, 0);

// ---------------------------------------------------------------------------
// Caption-height math, duplicated from QuickStrikeShared's internal (non-
// exported) CaptionOverlay helpers -- estimateWrappedLineCount,
// captionBlockHeight, and the caption's own CAPTION_* sizing constants.
// QuickStrikeShared.tsx is locked/consume-only (same rule IaDrangValleyQS.tsx
// follows for its own local duplicate of BOTTOM_SAFE_BUFFER), and none of this
// math is exported, so it's reproduced here verbatim rather than imported.
// Needed because the stacking swap requires GoldLowerThird to react to the
// ACTIVE caption cue's box height every frame, and CaptionOverlay has no way
// to report that back out.
// ---------------------------------------------------------------------------
const CAPTION_MAX_WIDTH = 900;
const CAPTION_H_PADDING = 20;
const CAPTION_V_PADDING = 10;
const CAPTION_FONT_SIZE = 38;
const CAPTION_LINE_HEIGHT = 1.3;
// Mirrors QuickStrikeShared's own (non-exported) BOTTOM_SAFE_BUFFER.
const BOTTOM_SAFE_BUFFER = 20;
// Visual gap kept between GoldLowerThird's box bottom and CaptionOverlay's
// box top -- same spirit as (not a literal copy of) CAPTION_HEADLINE_GAP,
// which measured from the headline's TEXT rather than its outer box edge
// because the caption used to be the one doing the avoiding; here GoldLowerThird
// is positioned via its own box-edge-anchored `bottomOffset`, so the gap is
// measured edge-to-edge instead.
const HEADLINE_CAPTION_GAP = 20;
// Passed as CaptionOverlay's `top` prop on every content slide. CaptionOverlay
// resolves its position as `Math.min(top, ceiling - height)` -- an
// unreachably large `top` forces it to always take the `ceiling - height`
// branch, i.e. hug SAFE_ZONE_BOTTOM_Y exactly and grow upward, regardless of
// cue length. No `overlayText` is passed to CaptionOverlay on these slides
// (that's the other half of the swap), so `ceiling` here is always the plain
// safe-zone line with no headline-avoidance math applied.
const CAPTION_HUG_BOTTOM_TOP = 999999;

// Verbatim copy of CaptionOverlay's internal estimateWrappedLineCount --
// replays the browser's own greedy line-wrap against the caption box's real
// font/width so the height computed below matches what CaptionOverlay itself
// will actually render.
function estimateWrappedLineCount(text: string, maxTextWidth: number, fontSize: number): number {
  if (typeof document === 'undefined') return 1;
  const ctx = document.createElement('canvas').getContext('2d');
  if (!ctx) return 1;
  ctx.font = `700 ${fontSize}px 'Oswald', Impact, 'Arial Black', sans-serif`;

  const words = text.split(/\s+/).filter(Boolean);
  let lineCount = 1;
  let lineWidth = 0;
  for (const word of words) {
    const wordWidth = ctx.measureText(`${word} `).width;
    if (lineWidth > 0 && lineWidth + wordWidth > maxTextWidth) {
      lineCount += 1;
      lineWidth = wordWidth;
    } else {
      lineWidth += wordWidth;
    }
  }
  return lineCount;
}

// Verbatim copy of CaptionOverlay's internal captionBlockHeight.
function captionBlockHeight(lineCount: number, fontSize: number): number {
  return lineCount * fontSize * CAPTION_LINE_HEIGHT + CAPTION_V_PADDING * 2;
}

// Verbatim copy of CaptionOverlay's internal cue-selection logic (word-count-
// proportional timing across audioDurationFrames) -- needed here so
// ContentSlide can know which cue CaptionOverlay itself will be showing at
// the current frame, to size the headline gap against the right cue.
function getActiveCaptionLine(lines: string[], frame: number, audioDurationFrames: number): string {
  const wordCounts = lines.map((line) => line.split(/\s+/).filter(Boolean).length);
  const totalWords = wordCounts.reduce((a, b) => a + b, 0);
  let wordsSoFar = 0;
  let startFrame = 0;
  for (const [i, line] of lines.entries()) {
    wordsSoFar += wordCounts[i];
    const endFrame = Math.round((wordsSoFar / totalWords) * audioDurationFrames);
    if (frame >= startFrame && frame < endFrame) return line;
    startFrame = endFrame;
  }
  return lines[lines.length - 1];
}

// ---------------------------------------------------------------------------
// HeadlineBox -- local replica of GoldLowerThird with its vertical padding
// trimmed ~25% (24px -> 18px). GoldLowerThird has no padding-override prop,
// and QuickStrikeShared.tsx is locked/consume-only, so this reproduces its
// exact visual design (same rule/box/text styling, same useGoldOverlay
// reveal timing, same bottomOffset-driven bottom-anchor positioning --
// copied verbatim from GoldLowerThird's own source) with ONLY the inner
// box's vertical padding changed. Horizontal padding (40px), font size/
// weight/family, text color, rule color/thickness, and box background
// color/opacity are all untouched, copied as-is. This does NOT change the
// stacking math from the previous fix -- bottomOffset still anchors the
// box's OUTER bottom edge (the padding trim only shrinks the box from
// there, it doesn't move the anchor itself), so ContentSlide's
// headlineBottomOffset computation below needs no changes. Also mirrors
// GoldLowerThird's own (now-additive) safeZoneBottomY prop, defaulting to
// the same module constant, so this local replica stays in sync with the
// shared component's API surface.
// ---------------------------------------------------------------------------
const HEADLINE_H_PADDING = 40; // unchanged, copied from GoldLowerThird's own '24px 40px'
const HEADLINE_V_PADDING = 18; // was 24px -- 25% reduction, per this fix

function HeadlineBox({
  text,
  frame,
  bottomOffset = 0,
  safeZoneBottomY = SAFE_ZONE_BOTTOM_Y,
}: {
  text: string;
  frame: number;
  bottomOffset?: number;
  safeZoneBottomY?: number;
}) {
  const { ruleWidth, textOpacity } = useGoldOverlay(frame);

  return (
    <AbsoluteFill
      style={{
        justifyContent: 'flex-end',
        alignItems: 'center',
        padding: `0 48px ${CANVAS_HEIGHT - safeZoneBottomY + BOTTOM_SAFE_BUFFER - bottomOffset}px`,
        pointerEvents: 'none',
      }}
    >
      <div style={{ width: '100%' }}>
        <div
          style={{
            height: 3,
            width: `${ruleWidth}%`,
            backgroundColor: GOLD,
            marginBottom: 16,
            marginLeft: 'auto',
            marginRight: 'auto',
          }}
        />
        <div
          style={{
            backgroundColor: 'rgba(0,0,0,0.60)',
            padding: `${HEADLINE_V_PADDING}px ${HEADLINE_H_PADDING}px`,
            textAlign: 'center',
          }}
        >
          <p
            style={{
              fontSize: 52,
              fontWeight: 700,
              color: '#F5F0E8',
              margin: 0,
              lineHeight: 1.25,
              textShadow: '0 2px 14px rgba(0,0,0,0.95)',
              fontFamily: "'Oswald', Impact, 'Arial Black', sans-serif",
              letterSpacing: '0.01em',
              opacity: textOpacity,
            }}
          >
            {text}
          </p>
        </div>
        <div
          style={{
            height: 3,
            width: `${ruleWidth}%`,
            backgroundColor: GOLD,
            marginTop: 16,
            marginLeft: 'auto',
            marginRight: 'auto',
          }}
        />
      </div>
    </AbsoluteFill>
  );
}

// ---------------------------------------------------------------------------
// ContentSlide -- replaces SlidePanel for slides 1-4 so the caption/headline
// stacking order can be reversed (see the top-of-file comment). Everything
// else (image/pan, vignette, context tag, cold-open/hard-cut opacity, audio)
// is identical to what SlidePanel already did, built from the same shared
// components.
// ---------------------------------------------------------------------------
function ContentSlide({
  slide,
  isFirst,
}: {
  slide: SlideConfig & { durationFrames: number; audioDurationFrames: number };
  isFirst: boolean;
}) {
  const frame = useCurrentFrame();
  const {
    durationFrames,
    audioDurationFrames,
    overlayText,
    image,
    captionLines,
    label,
    sourceWidth,
    sourceHeight,
    panFillMode,
    panDirection,
  } = slide;

  const opacity = isFirst
    ? 1
    : interpolate(frame, [0, HARD_CUT_FRAMES], [0, 1], {
        extrapolateLeft: 'clamp',
        extrapolateRight: 'clamp',
      });

  // Height of whatever caption cue CaptionOverlay is showing right now --
  // this is what GoldLowerThird needs to clear.
  const usableWidth = CAPTION_MAX_WIDTH - CAPTION_H_PADDING * 2;
  const activeCaptionHeight = captionLines
    ? captionBlockHeight(
        estimateWrappedLineCount(getActiveCaptionLine(captionLines, frame, audioDurationFrames), usableWidth, CAPTION_FONT_SIZE),
        CAPTION_FONT_SIZE,
      )
    : 0;

  // HeadlineBox's box bottom edge normally sits at
  // (safeZoneBottomY - BOTTOM_SAFE_BUFFER) + bottomOffset. CaptionOverlay's
  // box (hugging the same safe-zone line, per CAPTION_HUG_BOTTOM_TOP above)
  // has its own top edge at (safeZoneBottomY - BOTTOM_SAFE_BUFFER) -
  // activeCaptionHeight. Setting HeadlineBox's bottom edge to (caption's top
  // edge - gap) and solving for bottomOffset cancels the shared
  // (safeZoneBottomY - BOTTOM_SAFE_BUFFER) term entirely:
  //   bottomOffset = -(activeCaptionHeight + HEADLINE_CAPTION_GAP)
  // This cancellation holds for ANY safeZoneBottomY value, as long as
  // HeadlineBox and CaptionOverlay below are both given the SAME one --
  // which is why ANTIETAM_SAFE_ZONE_BOTTOM_Y only needs to be passed to
  // the two components below, with no change to this formula.
  const headlineBottomOffset = -(activeCaptionHeight + HEADLINE_CAPTION_GAP);

  return (
    <AbsoluteFill style={{ backgroundColor: '#000', opacity }}>
      {image && (
        <>
          <KenBurnsImage
            image={image}
            frame={frame}
            durationFrames={durationFrames}
            sourceWidth={sourceWidth}
            sourceHeight={sourceHeight}
            panFillMode={panFillMode}
            panDirection={panDirection}
          />
          <Vignette />
        </>
      )}

      {label && <ContextTag text={label} position="top-left" />}

      {overlayText && (
        <HeadlineBox
          text={overlayText}
          frame={frame}
          bottomOffset={headlineBottomOffset}
          safeZoneBottomY={ANTIETAM_SAFE_ZONE_BOTTOM_Y}
        />
      )}

      {captionLines && (
        <CaptionOverlay
          lines={captionLines}
          audioDurationFrames={audioDurationFrames}
          top={CAPTION_HUG_BOTTOM_TOP}
          safeZoneBottomY={ANTIETAM_SAFE_ZONE_BOTTOM_Y}
        />
      )}

      <Audio src={staticFile(slide.audio)} />
    </AbsoluteFill>
  );
}

// ---------------------------------------------------------------------------
// End card. Trigger word SHARPSBURG, subline points at the dedicated 5-Fact
// Antietam PDF (not the standing BLUEGRAY CTA_CONFIG subline, which points
// at the generic Civil War PDF) -- same one-off-subline pattern as
// BattleOfAtlantaQS's CTA_SUBLINE. Full VO ("Comment Sharpsburg. For the
// five-fact Antietam PDF. Follow for more.") is wired through EndCardCTA's
// own `audio` prop, so the whole card is voiced, not silent -- a deliberate
// departure from the other QuickStrikes' Max Alignment rule (VO limited to
// just the comment-trigger line) per this brief. "FOLLOW FOR MORE" below
// the card matches the established silent-badge wording used elsewhere
// (never "Follow Echo and Chronicle"), but is rendered at constant opacity
// here rather than the usual delayed reveal, and the whole EndCard skips
// the standard HARD_CUT_FRAMES entrance fade every other QuickStrike end
// card uses -- both per this brief's "no fade in/out on the end card" rule.
// ---------------------------------------------------------------------------
const CTA_SUBLINE = 'FOR THE 5-FACT ANTIETAM PDF';
const CTA_DURATION_S = CTA_AUDIO_S + PAD_S;
const CTA_FRAMES = Math.round(CTA_DURATION_S * FPS);
const CTA_AUDIO_FRAMES = Math.round(CTA_AUDIO_S * FPS);

function EndCard() {
  return (
    <AbsoluteFill>
      <EndCardCTA
        triggerWord="SHARPSBURG"
        subline={CTA_SUBLINE}
        audio="audio/antietam/slide5-endcard.mp3"
      />

      <CaptionOverlay
        lines={['Comment Sharpsburg.', 'For the five-fact Antietam PDF.', 'Follow for more.']}
        audioDurationFrames={CTA_AUDIO_FRAMES}
        top={200}
      />

      <AbsoluteFill
        style={{
          justifyContent: 'flex-end',
          alignItems: 'center',
          padding: '0 40px 90px',
          pointerEvents: 'none',
        }}
      >
        <div
          style={{
            color: GOLD,
            fontFamily: "'Oswald', Impact, 'Arial Black', sans-serif",
            fontSize: 26,
            letterSpacing: '0.08em',
            textTransform: 'uppercase',
            textAlign: 'center',
          }}
        >
          Follow for more
        </div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
}

export const totalDuration = slidesDuration + CTA_FRAMES;
export { FPS };

export default function AntietamQS() {
  let offset = 0;
  const froms = slidesWithFrames.map((s) => {
    const from = offset;
    offset += s.durationFrames;
    return from;
  });
  // slide 4 ends (audio + 0.4s pad) exactly where the end card begins --
  // `offset` here is the running total after the last story slide, i.e. the
  // same accumulator every other Sequence's `from` is derived from, so
  // there is no gap or overlap by construction.
  const ctaFrom = offset;

  return (
    <AbsoluteFill style={{ backgroundColor: '#000' }}>
      <style>{`@import url('${OSWALD_URL}');`}</style>

      {/* One-off music swap for this video only -- LincolnFortStevens's
          bed, not the standing Civil War Quick Strikes default
          (Gettysburg-Day1-music.mp3), which is unchanged everywhere else. */}
      <Audio src={staticFile('audio/LincolnFortStevens-music.mp3')} volume={0.15} loop />

      {slidesWithFrames.map((slide, i) => (
        <Sequence key={slide.id} from={froms[i]} durationInFrames={slide.durationFrames} layout="none">
          <ContentSlide slide={slide} isFirst={i === 0} />
        </Sequence>
      ))}

      <Sequence from={ctaFrom} durationInFrames={CTA_FRAMES} layout="none">
        <EndCard />
      </Sequence>
    </AbsoluteFill>
  );
}
